//THIS FILE IS AUTOGENERATED, DO NOT EDIT
use axum::{
    routing::{any, delete, get, head, options, patch, post, put, trace},
    Router,
};

#[path = "pages"]
pub mod pages {
    pub mod test;
    #[path = ":id"]
    pub mod param_id {
        pub mod dsa;
    }
}

pub async fn router() -> Router {
    let router = Router::new()
        .route("/", get(pages::test::test))
        .route("/:id", get(pages::param_id::dsa::test))
        .route("/:id", post(pages::param_id::dsa::test2))
        .route("/:id/siem", post(pages::param_id::dsa::test3));

    return router;
}
