const PAGES_DIR: &'static str = "src/pages";
const SCOPE_PATH: &'static str = "src/actix_scope.rs";

use anyhow::Result;
use qaf_build_utils::PageEntry;
use rust_format::{Formatter, RustFmt};
use std::path::PathBuf;

fn main() -> Result<()> {
    let pages = PathBuf::from(PAGES_DIR);

    let entries: PageEntry = PageEntry::generate(&pages)?;
    let mods_str = entries.get_mods_string()?;
    let services_str = generate_services(&entries, &pages);

    let services = format!(
        r#"
        pub fn generated_scope() -> actix_web::Scope {{
                web::scope("")
                {}
        }}
        "#,
        services_str
    );

    let mut main_template_content = format!(
        r#"
            //THIS FILE IS AUTOGENERATED, DO NOT EDIT
            use actix_web::web;
            
            #[path = "pages"]
            {}

            {}
        "#,
        mods_str, services
    );

    main_template_content = RustFmt::new().format_str(main_template_content)?;
    std::fs::write(SCOPE_PATH, main_template_content)?;

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=qaf.json");
    println!("cargo:rerun-if-changed=src/pages");

    Ok(())
}

pub fn generate_services(entry: &PageEntry, path: &PathBuf) -> String {
    let mut tmp = String::new();

    for child in &entry.children {
        let child_path = path.join(&child.name);
        if child.children.len() > 0 {
            tmp += &format!(".service(web::scope(\"{}\")\n", child.name);
            tmp += &generate_services(&child, &child_path);
            tmp += ")";
            continue;
        }

        let child_path = child_path.with_extension("rs");
        let use_path = path
            .to_str()
            .unwrap()
            .replacen("src/", "", 1)
            .replace("/", "::")
            .replace("{", "_")
            .replace("}", "_");

        for route in qaf_build_utils::get_file_routes(child_path).unwrap_or(vec![]) {
            tmp += &format!(
                ".service({}::{}::{})\n",
                use_path,
                child.name.replace("{", "_").replace("}", "_"),
                route.function
            );
        }
    }

    return tmp;
}
